export {getters as appGetters, mutations as appMutations} from "./app"
export {getters as asideGetters, mutations as asideMutations} from "./aside"
export {getters as headerGetters, mutations as headerMutations} from "./header"
export {getters as pageGetters, mutations as pageMutations} from "./page"
export {getters as tagsViewGetters, mutations as tagsViewMutations} from "./tagsView"
